### ISSUE TITLE
Research embedded http server/servlet container

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#1]
In order to provide a web-based gui without having to rely on an external service we need to research and select something that is either already a part of java or can be embedded within our application.

**Comment by kesslerk** [comment]
We looked into a couple http server/servlet containers. Tomcat and Jetty seemed like they would work best for us because they can be easily embedded into an application and they can be used as Maven plugins. Jetty is more light weight than Tomcat but Tomcat may be better to use because there are more online resources for it.

**Comment by MichaelTavener** [comment]
Can tomcat be run out of a single jar?

**Comment by mraynor** [comment]
Because it seems as if Tomcat won't work for us, how about using Jetty? As we said above, it can be used as Maven plugins and it seems like we can run Jetty from a single jar file on an app.

**Comment by JonathanKessler** [comment]
It looks as though you can embed Tomcat, albeit with multiple jar files. So it is an option, but not as lightweight as Jetty.

https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat
http://arhipov.blogspot.com/2011/03/embedded-tomcat-minimal-version.html

**Comment by mraynor** [comment]
I think we will try to use Jetty for server/servlet container.
