### ISSUE TITLE
Research logging frameworks

### ISSUE THREAD

**Issue by kesslerk** [VarenTechInternship/varentech-deploya#10]

**Comment by mraynor** [comment]
So we know logging can be used for debugging and/or collecting different stats while our app runs. We looked into LogBack and Log4j. It seems as if LogBack might be better because it has faster implementation and can implement SLF4J, which was recommended. We can also easily switch between LogBack and Log4j if needed.

**Comment by JonathanKessler** [comment]
I use logback with Slf4J on my project and find it easy to implement and change. You can even make changes to the logback.xml file that will change the way your application logs things (minimum log levels, names of log files, etc) without having to restart your application.

**Comment by mraynor** [comment]
Ok we will proceed using logback and Slf4J.
