### ISSUE TITLE
Research the database to use for this project

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#2]
It was suggested that we use SqlLite for this project's database, which is fine and would work. Spend some time research it and alternatives to be comfortable that you feel it is the best fit. If not, suggest alternatives here.

**Comment by mraynor** [comment]
SQLite seems like a good choice. SQLite is self-contained and server less. It is fast and efficient, and best of all, extremely portable in the sense that the entire database consists of a single file on a disk. It is also fairly easy to implement. On the other hand, MySQL might be another good option. A lot of websites can work on MySQL and it is one of the most popular of the large scale database servers ( a lot of online resources will be readily available).  MySQL supports a lot of SQL functionality as well. Because we can easily switch between databases, both of these seem like viable choices.

**Comment by lb-cake** [comment]
I think that SQLite is our best bet. It's lightweight and can be used for further functionality of the application, i.e. mobile app or desktop GUI.

With Tomcat 7 and higher, we can use SQLite.
http://stackoverflow.com/questions/4279632/how-to-configure-sqlite-in-tomcat-6
(Look in the top comments.)

With a SQLite plugin, we can also add JSON.

**Comment by MichaelTavener** [comment]
Sounds like we have a winner in SQLite.  Maybe document this choice on the wiki and close out this ticket?
