### ISSUE TITLE
Create an Archive Directory

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#22]
A temporary directory needs to be created in order for us to execute the jar file the user will give us. 

For convenience sake, I suggest, in a Linux environment the path to save the jar and execute it should be located at, "/opt/VarenTech/deploya/" + "Example.jar"

**Comment by JonathanKessler** [comment]
Please remember that the user should be able specify where on the filesystem to put the archive file as well as a command to unpack it. A default temporary directory would be fine if they don't have some directory already in mind for the file.

**Comment by lb-cake** [comment]
Correct, but do we need to store the jar/tar file locally first, in order to execute it?

**Comment by JonathanKessler** [comment]
Ahh sorry I misunderstood and also forgot we were storing a local copy. Wether or not to store a local copy should be configure and shouldn't be required in order to run a jar provided the user says where to actually deploy the jar. That being said If the user fails to specify a location, we will use a configurable location that will be different than the local storage to avoid overwriting previous versions.

So we are tracking  two locations:

Local storage for historic purposes
Deployment location. Deployment will be used to run things.

Jon Kessler
Varen Technologies

**Comment by lb-cake** [comment]
Thanks for the feed back Jon! I now know what to focus on. 

The method that I am thinking should:
1. Check to make sure that the archive file exists. If not, create one. I am going to say a default location will be at "/opt/VarenTech/deploya/".
2. Create a new directory that has the name of tar, zip, etc. file and a timestamp on it. 
3. Unpack the tar, zip, etc, file in that new directory.

**Comment by lb-cake** [comment]
This will be handled with the RPM. (I believe)

**Comment by MichaelTavener** [comment]
I posted this on #48 but pleeeease make the RPM distribution method optional. RPM requires root access and that's not something the majority of systems allow users to have.
