### ISSUE TITLE
JUnit4 Testing

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#33]
I know in our wiki we have JUnit Testing as one of our implementations, but we have yet to use it. 

This is something that I think would be really important to use as JUnit Testing...
Verifies the logic of a piece of a program is correct.
Running tests automatically help to identify software regressions introduced by changes in the source code. Therefore, having a high test coverage of our code allows us to continue developing features without having to perform lots of manual tests!!!!! 

I'll personally be looking into this, this weekend as I really want to do this for our code base.

**Comment by JonathanKessler** [comment]
I agree 100%. Concurrent unit test development or even developing unit tests before the methods you want to test themselves is a good habit to get into as it helps you ensure that you are writing simple units of work. If you have a method that cannot be easily or moderately easily tested then it may need to be redesigned or broken into smaller units of testable work.

The reason is when you have code that is easy to test, you have code that is easy to debug, maintain and enhance. Also, intellij has some good built in code coverage features so as you start to get these developer it will actually tell you how much of your codebase is tested.

@mraynor and @kesslerk , please read up on this and get into the habit of doing this as well. It may feel like it's slowing you down but it is absolutely worth it.

**Comment by mraynor** [comment]
We have successfully tested the renaming method, the method to get properties from the configuration file, and the REST urls connection, and the server connection!

**Comment by MichaelTavener** [comment]
Are the unit tests ready to be looked over by me or Jon?

**Comment by mraynor** [comment]
We made a branch called JUnitTesting with a few tests in it.

**Comment by kesslerk** [comment]
These still need a little work but they are merged to develop
