### ISSUE TITLE
ResearchBundle w/ Local Config File 

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#67]
This Config file should configure resources in the Jar without the user having to unpack the jar file.

**Comment by MichaelTavener** [comment]
I believe the app is already using a config file right?  A good interface might work like this:
- execute jar with `--export-config path/to/export/config.conf` that will write the config in the jar to the file system so that users wont have to create a config from scratch
- execute jar with `-c path/to/config/to/use/config.conf` to use a config other than the one shipped with the jar
- execute jar with `-h` or `--help` for help

**Comment by lb-cake** [comment]
This is handled in the External-Config-File Branch. Currently testing.

**Comment by lb-cake** [comment]
Replacing ResearchBundle with TypesafeConfig. Creating a new issue...
