### ISSUE TITLE
Allow app to be bound to localhost only.

### ISSUE THREAD

**Issue by MichaelTavener** [VarenTechInternship/varentech-deploya#92]
Allow the application to be bound to localhost only. This means that it will only respond to requests that come from the same system: localhost or 127.0.0.1.  This could be used to force authentication through a proxy.

**Comment by lb-cake** [comment]
Hey Tav, I believe that I restricted this application to run only on "127.0.0.1", but I am still unsure if it will work if I try connecting to this from a different proxy? Meaning, I do not know how to properly test this added functionality, since I can only run this application on a localhost. 

Any sort of insight would be greatly appreciated. The code that does this is located, [here](https://github.com/VarenTechInternship/varentech-deploya/blob/Bound-To-LocalHost/src/main/java/com/varentech/deploya/Main.java)

Check out line, 260 for the method that checks the local host.

**Comment by kesslerk** [comment]
Also, should this option be configurable? Should they have the option in the config file to only use localhost?

**Comment by MichaelTavener** [comment]
> Also, should this option be configurable?

Yup, should be configurable. 

Also, the link to the code is dead :/

**Comment by kesslerk** [comment]
Sorry, the code is [here](https://github.com/VarenTechInternship/varentech-deploya/blob/Login/src/main/java/com/varentech/deploya/Main.java). It starts at line 265.

**Comment by MichaelTavener** [comment]
That is definitely binding to localhost only, so its doing what we want! That being said, the method probably doen't need to be called "localHostCheck" since it will bind the server to whatever address you give it. But as is that definitely hits our target.
